config/routes.rb
Rails.application.routes.draw do
  root "pages#index"
  get "pages/home"
  get "pages/index"
  get "pages/manage"
  resources :inventories, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base.rb
class Base < ApplicationRecord
  has_many :links
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  has_many :links
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :inventory
  belongs_to :base
  delegate :name, :unit, to: :inventory, allow_nil: true, prefix: true
  delegate :name, to: :base, allow_nil: true, prefix: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @links = Link.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end

  def index; end

  def manage; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/inventories/_inventory.html.erb
<tr>
  <td class="center-cell"><%= inventory.sku %></td>
  <td class="center-cell"><%= inventory.name %></td>
  <td class="center-cell"><%= rand(10) %></td>
  <td class="center-cell"><%= inventory.unit %></td>
  <td class="center-cell">September 12, 2017 6:40 am</td>
  <p class = "btn btn-success pull-right"><%= "Delete" %></p>
</tr>

app/views/inventories/index.html.erb
<%= stylesheet_link_tag 'sidebar' %>
<div class="container">
  <div class="row">
    <%= render "layouts/sidebar" %>
    <div class="col-sm-9 col-md-9">
      <div class="well">
        <div class="row">
          <table class="table table-responsive table-hover">
            <thead>
              <tr class="info">
                <th class="text-center">CS</th>
                <th class="text-center">Tên mặt hàng</th>
                <th class="text-center">Số lượng</th>
                <th class="text-center">Đơn vị</th>
                <th class="text-center">Thay đổi</th>
              </tr>
            </thead>
            <tbody>
              <%= render @links %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="verybottom">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aligncenter">
            <ul class="social-network social-circle">
              <li><a href="#" class="icoRss" title="Rss"><i class="fa fa-rss"></i></a></li>
              <li><a href="#" class="icoFacebook" title="Facebook"><i class="fab fa-facebook"></i></a></li>
              <li><a href="#" class="icoTwitter" title="Twitter"><i class="fab fa-twitter"></i></a></li>
              <li><a href="#" class="icoGoogle" title="Google +"><i class="fab fa-google-plus"></i></a></li>
              <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fab fa-linkedin"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="aligncenter">
            <p>
            &copy;2018 Groovin - All right reserved | Developed by Socold</a>.
          </p>
        </div>
      </div>
    </div>
  </div>
</div>
</footer>

app/views/layouts/_header.html.erb
<div id="navigation" class="navbar navbar-inverse navbar-fixed-top default" role="navigation">
  <div class="container">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">5D COFFEE SHOP</a>
    </div>

    <div class="navigation">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"><nav>
        <ul class="nav navbar-nav navbar-right">
          <li class="current"><a href="#intro">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#works">Staff</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul></nav>
      </div><!-- /.navbar-collapse -->
    </div>

  </div>
</div>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<%= stylesheet_link_tag 'sidebar' %>

<div class="col-sm-3 col-md-3">
  <div class="panel-group" id="accordion">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-home">
          </span>Kho</a>
        </h4>
      </div>
      <div id="collapseOne" class="panel-collapse collapse in">
        <div class="panel-body">
          <table class="table">
            <tr>
              <td>
                <span class="glyphicon glyphicon-list-alt"></span>
                <%= link_to "Quản lý", inventories_path %>
              </td>
            </tr>
            <tr>
              <td>
                <span class="glyphicon glyphicon-chevron-right"></span>
                <%= link_to "Chuyển", inventories_path %>
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
          </span>Modules</a>
        </h4>
      </div>
      <div id="collapseTwo" class="panel-collapse collapse">
        <div class="panel-body">
          <table class="table">
            <tr>
              <td>
                <a href="http://www.jquery2dotnet.com">Orders</a> <span class="label label-success">$ 320</span>
              </td>
            </tr>
            <tr>
              <td>
                <a href="http://www.jquery2dotnet.com">Invoices</a>
              </td>
            </tr>
            <tr>
              <td>
                <a href="http://www.jquery2dotnet.com">Shipments</a>
              </td>
            </tr>
            <tr>
              <td>
                <a href="http://www.jquery2dotnet.com">Tex</a>
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">
          </span>Account</a>
        </h4>
      </div>
      <div id="collapseThree" class="panel-collapse collapse">
        <div class="panel-body">
          <table class="table">
            <tr>
              <td>
                <a href="http://www.jquery2dotnet.com">Change Password</a>
              </td>
            </tr>
            <tr>
              <td>
                <a href="http://www.jquery2dotnet.com">Notifications</a> <span class="label label-info">5</span>
              </td>
            </tr>
            <tr>
              <td>
                <a href="http://www.jquery2dotnet.com">Import/Export</a>
              </td>
            </tr>
            <tr>
              <td>
                <span class="glyphicon glyphicon-trash text-danger"></span><a href="http://www.jquery2dotnet.com" class="text-danger">
                Delete Account</a>
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><span class="glyphicon glyphicon-file">
          </span>Reports</a>
        </h4>
      </div>
      <div id="collapseFour" class="panel-collapse collapse">
        <div class="panel-body">
          <table class="table">
            <tr>
              <td>
                <span class="glyphicon glyphicon-usd"></span><a href="http://www.jquery2dotnet.com">Sales</a>
              </td>
            </tr>
            <tr>
              <td>
                <span class="glyphicon glyphicon-user"></span><a href="http://www.jquery2dotnet.com">Customers</a>
              </td>
            </tr>
            <tr>
              <td>
                <span class="glyphicon glyphicon-tasks"></span><a href="http://www.jquery2dotnet.com">Products</a>
              </td>
            </tr>
            <tr>
              <td>
                <span class="glyphicon glyphicon-shopping-cart"></span><a href="http://www.jquery2dotnet.com">Shopping Cart</a>
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>5D Coffee</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="Just for fun" />
  <meta name="author" content="Socold" />
  <%= favicon_link_tag "/images/favicon.ico" %>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application",
    "data-turbolinks-track": "reload" %>
  <%= stylesheet_link_tag "fancybox/jquery.fancybox" %>
  <%= stylesheet_link_tag "style" %>
  <%= stylesheet_link_tag "slippry" %>
  <%= stylesheet_link_tag "custom-fonts" %>
  <%= stylesheet_link_tag "bootstrap-theme" %>
  <%= stylesheet_link_tag "animate" %>
  <%= stylesheet_link_tag "prettyPhoto" %>
  <%= stylesheet_link_tag "overwrite" %>
  <%= stylesheet_link_tag "fancybox" %>
  <%= stylesheet_link_tag "default" %>
  <%= stylesheet_link_tag "custom" %>
  <%= stylesheet_link_tag "bootstrap.min" %>
  <%= stylesheet_link_tag "bootstrap" %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
</head>

<body>
  <%= render "layouts/header" %>
  <%= yield %>
  <%= render "layouts/footer" %>
</body>
</html>

app/views/links/_link.html.erb
<tr>
  <td class="text-center"><%= link.base_name %></td>
  <td class="text-center"><%= link.inventory_name %></td>
  <td class="text-center"><%= link.quantity %></td>
  <td class="text-center"><%= link.inventory_unit %></td>
  <td class="text-center">September 12, 2017 6:40 am</td>
</tr>

app/views/page/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>5D Coffee</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="Just for fun" />
  <meta name="author" content="Socold" />
</head>
<body>
  <!-- section intro -->
  <section id="intro">
    <ul id="slippry-slider">
      <li>
        <a href="#slide1"><img src="/images/slide/1.jpg"></a>
      </li>
      <li>
        <a href="#slide2"><img src="/images/slide/2.jpg"></a>
      </li>
      <li>
        <a href="#slide3"><img src="/images/slide/3.jpg"></a>
      </li>
    </ul>
  </section>
  <!-- end intro -->
  <!-- Section about -->
  <section id="about" class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="heading">
            <h3><span>About us</span></h3>
          </div>
          <div class="sub-heading">
            <p>
             Since you came here, you became one of us
           </p>
         </div>
       </div>
     </div>
     <div class="row">
      <div class="col-md-3">
        <div class="team-box">
          <img src="/images/dummies/coffee.jpg" alt="" class="img-responsive shop-image" />
          <div class="roles">
            <h5><strong>5D Coffee Shop</strong></h5>
            <p>
              72 Le Dinh Duong St.
            </p>
            <ul class="social-profile">
              <li><a href="https://www.facebook.com/5dcoffeeshop/"><i class="fab fa-facebook fa-lg"></i></a></li>
              <li><a href="#"><i class="fab fa-instagram fa-lg"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="team-box">
          <img src="/images/dummies/dorm.jpg" alt="" class="img-responsive shop-image" />
          <div class="roles">
            <h5><strong>5D Upper Dorm</strong></h5>
            <p>
              155 Trieu Nu Vuong St.
            </p>
            <ul class="social-profile">
              <li><a href="#"><i class="fab fa-facebook fa-lg"></i></a></li>
              <li><a href="#"><i class="fab fa-instagram fa-lg"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="team-box">
          <img src="/images/dummies/kitchen.jpg" alt="" class="img-responsive shop-image" />
          <div class="roles">
            <h5><strong>Chin's Kitchen</strong></h5>
            <p>
              154 Trieu Nu Vuong St.
            </p>
            <ul class="social-profile">
              <li><a href="#"><i class="fab fa-facebook fa-lg"></i></a></li>
              <li><a href="#"><i class="fab fa-instagram fa-lg"></i></a></li></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="team-box">
          <img src="/images/dummies/local.jpg" alt="" class="img-responsive shop-image" />
          <div class="roles">
            <h5><strong>The Local Beans</strong></h5>
            <p>
              Le Hong Phong St.
            </p>
            <ul class="social-profile">
              <li><a href="#"><i class="fab fa-facebook fa-lg"></i></a></li>
              <li><a href="#"><i class="fab fa-instagram fa-lg"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end section about -->

<!-- Section gallery -->
<section>
  <div class="heading">
    <h3><span>Our gallery</span></h3>
  </div>
  <div class="sub-heading">
    <p>
     Save the day, save the moment
   </p>
 </div>
 <div class="container gal-container">
  <div class="col-md-8 col-sm-12 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#1">
        <img src="/images/gallery/1.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#2">
        <img src="/images/gallery/2.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#3">
        <img src="/images/gallery/3.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#4">
        <img src="/images/gallery/4.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#5">
        <img src="/images/gallery/5.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#6">
        <img src="/images/gallery/6.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#7">
        <img src="/images/gallery/7.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#8">
        <img src="/images/gallery/8.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#9">
        <img src="/images/gallery/9.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-8 col-sm-12 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#10">
        <img src="/images/gallery/10.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#11">
        <img src="/images/gallery/11.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#12">
        <img src="/images/gallery/12.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#13">
        <img src="/images/gallery/13.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#14">
        <img src="/images/gallery/14.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#15">
        <img src="/images/gallery/15.jpg">
      </a>
    </div>
  </div>
  <div class="col-md-4 col-sm-6 co-xs-12 gal-item">
    <div class="box">
      <a href="#" data-toggle="modal" data-target="#16">
        <img src="/images/gallery/16.jpg">
      </a>
    </div>
  </div>
</div>
</section>
<!-- end section gallery -->

<!-- section contact -->
<section id="contact" class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="heading">
          <h3><span>Get in touch</span></h3>
        </div>
        <div class="sub-heading">
          <p>
            Please let us know if you need any further information :D
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h4><i class="icon-envelope"></i><strong>Contact form</strong></h4>
        <p>
          Want to work with us or just want to say hello? Don't hesitate to get in touch!
        </p>
        <!-- start contact form -->
        <div class="cform" id="contact-form">
          <div id="sendmessage">
           Your message has been sent. Thank you!
         </div>
         <form action="contact/contact.php" method="post" role="form" class="contactForm">
          <div class="form-group">
            <label for="name">Your Name</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="maxlen:4" data-msg="Please enter at least 4 chars" />
            <div class="validation"></div>
          </div>
          <div class="form-group">
            <label for="email">Your Email</label>
            <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
            <div class="validation"></div>
          </div>
          <div class="form-group">
            <label for="subject">Subject</label>
            <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="maxlen:4" data-msg="Please enter at least 8 chars of subject" />
            <div class="validation"></div>
          </div>
          <div class="form-group">
            <label for="message">Message</label>
            <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us"></textarea>
            <div class="validation"></div>
          </div>

          <button type="submit" class="btn btn-lg btn-theme pull-left">Send Message</button>
        </form>

      </div>
      <!-- end contact form -->
      <div class="clear"></div>
    </div>
    <div class="col-md-6">
      <h4>Find our location</h4>
      <p>View from google map</p>
      <!-- map -->
      <div id="section-map" class="clearfix">
        <div id="map"></div>
      </div>
    </div>
  </div>
</div>
</section>
<!-- end section contact -->

<a href="#" class="scrollup"><i class="fa fa-angle-up fa-2x"></i></a>
<!-- javascript -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC_yQ0GJfffLlAEr6O6ZsHJesQGuPKjlIg"></script>
<script>
  $(document).ready(function(){
    $('#slippry-slider').slippry(
      defaults = {
        transition: 'vertical',
        useCSS: true,
        speed: 5000,
        pause: 3000,
        initSingle: false,
        auto: true,
        preload: 'visible',
        pager: false,
      }
      )
  });
</script>

<script type="text/javascript">
    // When the window has finished loading create our google map below
    google.maps.event.addDomListener(window, 'load', init);

    function init() {
      var myLatLng = {lat: 16.063289, lng: 108.217443};

      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 15,
        center: myLatLng
      });

      var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: "5D Upper Dorm"
      });
    }
  </script>
</body>
</html>

app/views/pages/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>
<%= link_to "asd","google.com", class: "btn btn-success" %>

app/views/pages/manage.html.erb
<%= stylesheet_link_tag 'sidebar' %>

<div class="container">
  <div class="row">
    <div class="col-sm-3 col-md-3">
      <div class="panel-group" id="accordion">

        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-folder-close">
              </span>Storage</a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
              <table class="table">
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-pencil text-primary"></span><a href="http://www.jquery2dotnet.com">Manage</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-flash text-success"></span><a href="http://www.jquery2dotnet.com">Add</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-file text-info"></span><a href="http://www.jquery2dotnet.com">Newsletters</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-comment text-success"></span><a href="http://www.jquery2dotnet.com">Comments</a>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>

        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
              </span>Modules</a>
            </h4>
          </div>
          <div id="collapseTwo" class="panel-collapse collapse">
            <div class="panel-body">
              <table class="table">
                <tr>
                  <td>
                    <a href="http://www.jquery2dotnet.com">Orders</a> <span class="label label-success">$ 320</span>
                  </td>
                </tr>
                <tr>
                  <td>
                    <a href="http://www.jquery2dotnet.com">Invoices</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <a href="http://www.jquery2dotnet.com">Shipments</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <a href="http://www.jquery2dotnet.com">Tex</a>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">
              </span>Account</a>
            </h4>
          </div>
          <div id="collapseThree" class="panel-collapse collapse">
            <div class="panel-body">
              <table class="table">
                <tr>
                  <td>
                    <a href="http://www.jquery2dotnet.com">Change Password</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <a href="http://www.jquery2dotnet.com">Notifications</a> <span class="label label-info">5</span>
                  </td>
                </tr>
                <tr>
                  <td>
                    <a href="http://www.jquery2dotnet.com">Import/Export</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-trash text-danger"></span><a href="http://www.jquery2dotnet.com" class="text-danger">
                    Delete Account</a>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><span class="glyphicon glyphicon-file">
              </span>Reports</a>
            </h4>
          </div>
          <div id="collapseFour" class="panel-collapse collapse">
            <div class="panel-body">
              <table class="table">
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-usd"></span><a href="http://www.jquery2dotnet.com">Sales</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-user"></span><a href="http://www.jquery2dotnet.com">Customers</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-tasks"></span><a href="http://www.jquery2dotnet.com">Products</a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <span class="glyphicon glyphicon-shopping-cart"></span><a href="http://www.jquery2dotnet.com">Shopping Cart</a>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-9 col-md-9">
      <div class="well">
        <h1>
        Accordion Menu With Icon</h1>
        Admin Dashboard Accordion Menu
      </div>
    </div>
  </div>
</div>